services:
  aps_postgres:
    image: postgres
    restart: always
    ports:
      - 3333:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
  aps:
    build:
      context: ../
      dockerfile: ./ActivityPlannerService/Dockerfile
    ports:
      - 8100:8100
    env_file:
      - .env
    depends_on:
      - aps_postgres

volumes:
  postgres: